In [1]:
from datetime import date

import pandas as pd
from IPython.display import Markdown

from data import PROGRAMS
from models import AVAILABILITY_TYPES, COUNTRIES, Semester

In [2]:
display(Markdown(f"## This notebook is run on {date.today()}"))

## This notebook is run on 2026-04-30

In [3]:
TARGET_SEMESTER = Semester(starting_year="2026", season="winter")

In [4]:
programs = pd.DataFrame(
    [
        {
            "name": p.name,
            "university": p.university_name,
            "country": p.country,
            "availability": p.get_availability(TARGET_SEMESTER),
            "application_fee": p.application_fee,
            "window_start": p.get_days_until_window_starts(TARGET_SEMESTER),
            "window_end": p.get_days_until_window_ends(TARGET_SEMESTER),
            "specializations": p.specializations,
        }
        for p in PROGRAMS
    ]
)

In [5]:
for a in AVAILABILITY_TYPES:
    display(Markdown(f"## {a.upper()}"))
    display(programs[programs["availability"] == a])

## CLOSED

,name,university,country,availability,application_fee,window_start,window_end,specializations
0,Computer Science,University of Stuttgart,Germany,closed,0.0,-166.0,-105,"[Autonomous Systems in Computer Science, Servi..."
2,Computer Science,University of Siegen,Germany,closed,0.0,-119.0,0,"[Complex and Intelligent Software Systems, Emb..."
7,Computer Science,Ruhr University Bochum,Germany,closed,NaN,-180.0,-136,"[Artificial Intelligence, Cybersecurity, Quant..."
14,Computer and Information Science,University of Konstanz,Germany,closed,NaN,-43.0,-15,"[Algorithmics, Data science, Interactive syste..."
15,Applied Computer Science,University of Goettingen,Germany,closed,0.0,-46.0,-15,"[Applied System Engineering, Bioinformatics, B..."
17,Software Systems Engineering,RWTH Aachen University,Germany,closed,0.0,-150.0,-60,"[Applied Computer Science, Communication, Data..."
23,Cognitive Science,Rhineland-Palatinate Technical University of K...,Germany,closed,60.0,-66.0,0,"[Cognition and Knowledge, Cognitive Neuroscien..."
25,Cognitive Science,Technical University of Darmstadt,Germany,closed,NaN,-150.0,-60,"[Applied Cognitive Science, Artificial Intelli..."
28,Neural and Behavioural Sciences,University of Tuebingen,Germany,closed,NaN,NaN,-30,"[Brain Imaging and Recording, Cognitive Neuros..."
29,Neuroscience,University of Oldenburg,Germany,closed,30.0,-46.0,0,"[Behavioural Neuroscience, Computational Neuro..."
30,Neuroscience,University of Bremen,Germany,closed,NaN,-60.0,0,"[Computational Neuroscience, Experimental Neur..."
32,Computer Science,University of Bari Aldo Moro,Italy,closed,NaN,NaN,-61,"[Artificial Intelligence, Security Engineering]"
33,Computer Science,University of Camerino,Italy,closed,20.0,NaN,-30,"[Artificial Intelligence, Business Information..."
34,Computer Science,University of Genoa,Italy,closed,30.0,-155.0,-41,"[Data Science & Engineering, Software Security..."
35,Computer Science and Engineering,Politecnico di Milano,Italy,closed,NaN,-107.0,-63,"[Ambient and data intelligence, Artificial int..."
38,Computer Science,University of Pisa,Italy,closed,30.0,-150.0,-84,"[Artificial Intelligence, Big Data Technologie..."
40,Computer Science,University of Trento,Italy,closed,30.0,NaN,-57,"[Computer Science and Technologies, ICT Innova..."
41,Software Engineering,Free University of Bozen-Bolzano,Italy,closed,50.0,-59.0,-2,None

## NOT-OPENED

,name,university,country,availability,application_fee,window_start,window_end,specializations
1,Computer Science,Technical University of Hamburg,Germany,not-opened,0.0,32.0,76,"[Computer and Software Engineering, Intelligen..."
9,Computer Science,University of Marburg,Germany,not-opened,30.0,1.0,61,"[Artificial Intelligence, Cloud Computing, Dat..."
18,International Software Systems Science,Bamberg University,Germany,not-opened,0.0,15.0,76,"[Communication Systems and Protocols, Distribu..."
21,Cognitive Science,Ruhr University Bochum,Germany,not-opened,NaN,32.0,76,"[Brain and Behavior, Computation and Artificia..."
22,Cognitive Science,University of Osnabrueck,Germany,not-opened,30.0,7.0,46,"[Cognition: (Computational) Neuroscience, Cogn..."

## OPENED

,name,university,country,availability,application_fee,window_start,window_end,specializations
3,Computer Science,University of Bonn,Germany,opened,0.0,-15.0,1,"[Algorithmics, Graphics/Vision/Audio, Informat..."
4,Computer Science,University of Hannover,Germany,opened,30.0,-15.0,31,"[Data Science, Human Centered Computing, Syste..."
6,Computer Science,University of Regensburg,Germany,opened,30.0,-15.0,32,"[Bioinformatics, Core Computer Science, Human-..."
10,Computer Science,University of Freiburg,Germany,opened,0.0,-15.0,31,"[Artificial Intelligence, Cyber-Physical Systems]"
11,Computer Science International,University of Rostock,Germany,opened,30.0,-29.0,31,"[Complex Systems, Information Systems]"
12,Computer Science,University of Potsdam,Germany,opened,0.0,-29.0,32,"[Algorithms and Foundations, Data and AI, Digi..."
19,Software Engineering,University of Hildesheim,Germany,opened,30.0,-15.0,61,"[Advanced Web Development, Model-Based Softwar..."
20,Web Engineering,Chemnitz University of Technology,Germany,opened,30.0,-29.0,76,"[Databases, Information Systems, Internet and ..."
24,Cognitive Science,University of Potsdam,Germany,opened,0.0,-29.0,32,"[Advanced Natural Language Processing, Cogniti..."
26,Cognitive Systems,University of Ulm,Germany,opened,30.0,-29.0,15,"[Interaction, Learning and Memory, Methods, Ge..."
27,"Mind, Brain and Behavior",University of Giessen,Germany,opened,30.0,-150.0,46,"[Current Topics in Cognition and Development, ..."
31,Cognitive Science,University of Trento,Italy,opened,30.0,-80.0,29,"[Cognitive Neuroscience, Computational and The..."
36,Engineering in Computer Science,University of Messina,Italy,opened,30.0,-17.0,10,None
37,Computer Science,University of Padua,Italy,opened,60.0,-59.0,2,None
39,Computer Science,Sapienza University of Rome,Italy,opened,30.0,-129.0,15,None

## NOT-CLOSED

,name,university,country,availability,application_fee,window_start,window_end,specializations
5,Computer Science,Karlsruhe Institute of Technology,Germany,not-closed,NaN,NaN,46,"[Algorithm Engineering, Computer Graphics and ..."
8,Computer Science,Paderborn University,Germany,not-closed,30.0,NaN,31,"[Classical and Quantum Algorithm Design, Compu..."
13,Computer Science,Saarland University,Germany,not-closed,NaN,NaN,15,"[Cryptography, Distributed Information and Com..."
16,Web and Data Science,University of Koblenz,Germany,not-closed,30.0,NaN,46,"[Data Science, Engineering Web and Data-intens..."

In [6]:
display(Markdown("## Applicable Programs Sorted by Days until Window Closes"))

for country in COUNTRIES:
    display(Markdown(f"### {country}"))
    with pd.option_context("display.max_colwidth", None):
        display(
            programs[(programs["window_end"] >= 0) & (programs["country"] == country)]
            .assign(
                specializations=lambda d: d["specializations"].map(
                    lambda x: ", ".join(x) if isinstance(x, (list, tuple, set)) else x
                )
            )
            .sort_values(by=["window_end", "application_fee", "window_start"])
        )

# with pd.option_context("display.max_colwidth", None):
#     display(Markdown("## Applicable Programs' Specialiaztions"))
#     display(
#         programs[programs["window_end"] >= 0].assign(
#             specializations=lambda d: d["specializations"].map(
#                 lambda x: ", ".join(x) if isinstance(x, (list, tuple, set)) else x
#             )
#         )[["name", "university", "specializations"]]
#     )

## Applicable Programs Sorted by Days until Window Closes

### Germany

,name,university,country,availability,application_fee,window_start,window_end,specializations
2,Computer Science,University of Siegen,Germany,closed,0.0,-119.0,0,"Complex and Intelligent Software Systems, Embedded Systems, Visual Computing"
29,Neuroscience,University of Oldenburg,Germany,closed,30.0,-46.0,0,"Behavioural Neuroscience, Computational Neuroscience, Sensory Neuroscience"
23,Cognitive Science,Rhineland-Palatinate Technical University of Kaiserslautern-Landau,Germany,closed,60.0,-66.0,0,"Cognition and Knowledge, Cognitive Neuroscience, Computation, Language and Linguistics, Perception"
30,Neuroscience,University of Bremen,Germany,closed,NaN,-60.0,0,"Computational Neuroscience, Experimental Neuroscience"
3,Computer Science,University of Bonn,Germany,opened,0.0,-15.0,1,"Algorithmics, Graphics/Vision/Audio, Information and Communication Management, Intelligent Systems"
26,Cognitive Systems,University of Ulm,Germany,opened,30.0,-29.0,15,"Interaction, Learning and Memory, Methods, General Concepts and Tools, Perception, Planning and Reasoning"
13,Computer Science,Saarland University,Germany,not-closed,NaN,NaN,15,"Cryptography, Distributed Information and Communications Systems, Image Processing, Language Processing, Multimedia Applications, Program Analysis and Formal Methods"
10,Computer Science,University of Freiburg,Germany,opened,0.0,-15.0,31,"Artificial Intelligence, Cyber-Physical Systems"
11,Computer Science International,University of Rostock,Germany,opened,30.0,-29.0,31,"Complex Systems, Information Systems"
4,Computer Science,University of Hannover,Germany,opened,30.0,-15.0,31,"Data Science, Human Centered Computing, Systems-oriented Computer Science"
8,Computer Science,Paderborn University,Germany,not-closed,30.0,NaN,31,"Classical and Quantum Algorithm Design, Computer and Communication Systems, Data Science and Intelligent Systems, Security, Software Engineering"
12,Computer Science,University of Potsdam,Germany,opened,0.0,-29.0,32,"Algorithms and Foundations, Data and AI, Digital Health, Security Engineering, Systems"
24,Cognitive Science,University of Potsdam,Germany,opened,0.0,-29.0,32,"Advanced Natural Language Processing, Cognition, Cognitive Development, Cognitive Modeling, Cognitive Neuroscience, Evidence Bases for Language Disorders, First Language Acquisition, Language Processing"
6,Computer Science,University of Regensburg,Germany,opened,30.0,-15.0,32,"Bioinformatics, Core Computer Science, Human-Centred Computing, Information Systems"
27,"Mind, Brain and Behavior",University of Giessen,Germany,opened,30.0,-150.0,46,"Current Topics in Cognition and Development, Perception and Action, Visual Cognition and Object Perception, Visual Perception of Color and Materials"
22,Cognitive Science,University of Osnabrueck,Germany,not-opened,30.0,7.0,46,"Cognition: (Computational) Neuroscience, Cognition: Artificial Intelligence and Machine Learning, Cognition: Mind, Ethics, and Society, Cognition: Psychology, Language, and Communication"
16,Web and Data Science,University of Koblenz,Germany,not-closed,30.0,NaN,46,"Data Science, Engineering Web and Data-intensive Systems, Machine Learning and Data Mining, Network Theory and Dynamic Systems, Web Science"
5,Computer Science,Karlsruhe Institute of Technology,Germany,not-closed,NaN,NaN,46,"Algorithm Engineering, Computer Graphics and Geometry Processing, Data Science, Design of Embedded Systems and Computer Architectures, Human-centred Machine Intelligence, Parallel Computing, Robotics and Automation, Software Engineering and Compiler Construction, Telematics, Theoretical Foundations"
19,Software Engineering,University of Hildesheim,Germany,opened,30.0,-15.0,61,"Advanced Web Development, Model-Based Software Engineering, Requirements Engineering for Quality, Software Architectures, Software Engineering, Software Product Line Engineering"
9,Computer Science,University of Marburg,Germany,not-opened,30.0,1.0,61,"Artificial Intelligence, Cloud Computing, Databases, Distributed Systems, Graphics Programming, IT Security, Model Checking, Software Design"
18,International Software Systems Science,Bamberg University,Germany,not-opened,0.0,15.0,76,"Communication Systems and Protocols, Distributed and Mobile Systems, Service-oriented Architectures, Software Analysis and Verification"
1,Computer Science,Technical University of Hamburg,Germany,not-opened,0.0,32.0,76,"Computer and Software Engineering, Intelligence Engineering, Mathematics"
20,Web Engineering,Chemnitz University of Technology,Germany,opened,30.0,-29.0,76,"Databases, Information Systems, Internet and Web Technologies, Software Engineering"
21,Cognitive Science,Ruhr University Bochum,Germany,not-opened,NaN,32.0,76,"Brain and Behavior, Computation and Artificial Intelligence, Mind and Language"

### Italy

,name,university,country,availability,application_fee,window_start,window_end,specializations
37,Computer Science,University of Padua,Italy,opened,60.0,-59.0,2,NaN
36,Engineering in Computer Science,University of Messina,Italy,opened,30.0,-17.0,10,NaN
39,Computer Science,Sapienza University of Rome,Italy,opened,30.0,-129.0,15,NaN
31,Cognitive Science,University of Trento,Italy,opened,30.0,-80.0,29,"Cognitive Neuroscience, Computational and Theoretical Modelling of Language and Cognition, fundamental Behavioural Neuroscience"