In [1]:
import pandas as pd
from IPython.display import Markdown

from data import PROGRAMS
from models import AVAILABILITY_TYPES, Semester

In [2]:
TARGET_SEMESTER = Semester(starting_year="2026", season="winter")

In [3]:
programs = pd.DataFrame(
    [
        {
            "name": p.name,
            "university": p.university_name,
            "availability": p.get_availability(TARGET_SEMESTER),
            "application_fee": p.application_fee,
            "window_start": p.get_days_until_window_starts(TARGET_SEMESTER),
            "window_end": p.get_days_until_window_ends(TARGET_SEMESTER),
            "specializations": p.specializations,
        }
        for p in PROGRAMS
    ]
)

In [4]:
for a in AVAILABILITY_TYPES:
    display(Markdown(f"## {a.upper()}"))
    display(programs[programs["availability"] == a])

## CLOSED

,name,university,availability,application_fee,window_start,window_end,specializations
0,Computer Science,University of Stuttgart,closed,0,-122.0,-61,"[Autonomous Systems in Computer Science, Servi..."
7,Computer Science,Ruhr University Bochum,closed,None,-136.0,-92,"[Artificial Intelligence, Cybersecurity, Quant..."
17,Software Systems Engineering,RWTH Aachen University,closed,0,-106.0,-16,"[Applied Computer Science, Communication, Data..."
25,Cognitive Science,Technical University of Darmstadt,closed,None,-106.0,-16,"[Applied Cognitive Science, Artificial Intelli..."

## NOT-OPENED

,name,university,availability,application_fee,window_start,window_end,specializations
1,Computer Science,Technical University of Hamburg,not-opened,0,76.0,120,"[Computer and Software Engineering, Intelligen..."
3,Computer Science,University of Bonn,not-opened,0,29.0,45,"[Algorithmics, Graphics/Vision/Audio, Informat..."
4,Computer Science,University of Hannover,not-opened,75/30,29.0,75,"[Data Science, Human Centered Computing, Syste..."
6,Computer Science,University of Regensburg,not-opened,75/30,29.0,76,"[Bioinformatics, Core Computer Science, Human-..."
9,Computer Science,University of Marburg,not-opened,75/30,45.0,105,"[Artificial Intelligence, Cloud Computing, Dat..."
10,Computer Science,University of Freiburg,not-opened,0,29.0,75,"[Artificial Intelligence, Cyber-Physical Systems]"
11,Computer Science International,University of Rostock,not-opened,75/30,15.0,75,"[Complex Systems, Information Systems]"
12,Computer Science,University of Potsdam,not-opened,0,15.0,76,"[Algorithms and Foundations, Data and AI, Digi..."
14,Computer and Information Science,University of Konstanz,not-opened,None,1.0,29,"[Algorithmics, Data science, Interactive syste..."
18,International Software Systems Science,Bamberg University,not-opened,0,59.0,120,"[Communication Systems and Protocols, Distribu..."
19,Software Engineering,University of Hildesheim,not-opened,75/30,29.0,105,"[Advanced Web Development, Model-Based Softwar..."
20,Web Engineering,Chemnitz University of Technology,not-opened,75/30,15.0,120,"[Databases, Information Systems, Internet and ..."
21,Cognitive Science,Ruhr University Bochum,not-opened,None,76.0,120,"[Brain and Behavior, Computation and Artificia..."
22,Cognitive Science,University of Osnabrueck,not-opened,75/30,51.0,90,"[Cognition: (Computational) Neuroscience, Cogn..."
24,Cognitive Science,University of Potsdam,not-opened,0,15.0,76,"[Advanced Natural Language Processing, Cogniti..."
26,Cognitive Systems,University of Ulm,not-opened,75/30,15.0,59,"[Interaction, Learning and Memory, Methods, Ge..."

## OPENED

,name,university,availability,application_fee,window_start,window_end,specializations
2,Computer Science,University of Siegen,opened,0,-75.0,44,"[Complex and Intelligent Software Systems, Emb..."
15,Applied Computer Science,University of Goettingen,opened,0,-2.0,29,"[Applied System Engineering, Bioinformatics, B..."
23,Cognitive Science,Rhineland-Palatinate Technical University of K...,opened,60,-22.0,44,"[Cognition and Knowledge, Cognitive Neuroscien..."
27,"Mind, Brain and Behavior",University of Giessen,opened,75/30,-106.0,90,"[Current Topics in Cognition and Development, ..."
29,Neuroscience,University of Oldenburg,opened,75/30,-2.0,44,"[Behavioural Neuroscience, Computational Neuro..."
30,Neuroscience,University of Bremen,opened,None,-16.0,44,"[Computational Neuroscience, Experimental Neur..."

## NOT-CLOSED

,name,university,availability,application_fee,window_start,window_end,specializations
5,Computer Science,Karlsruhe Institute of Technology,not-closed,None,NaN,90,"[Algorithm Engineering, Computer Graphics and ..."
8,Computer Science,Paderborn University,not-closed,75/30,NaN,75,"[Classical and Quantum Algorithm Design, Compu..."
13,Computer Science,Saarland University,not-closed,None,NaN,59,"[Cryptography, Distributed Information and Com..."
16,Web and Data Science,University of Koblenz,not-closed,75/30,NaN,90,"[Data Science, Engineering Web and Data-intens..."
28,Neural and Behavioural Sciences,University of Tuebingen,not-closed,None,NaN,14,"[Brain Imaging and Recording, Cognitive Neuros..."

In [5]:
display(Markdown("## Applicable Programs Sorted by Days until Window Closes"))
display(
    programs[programs["window_end"] >= 0].sort_values(
        by=["window_end", "application_fee", "window_start"]
    )
)

## Applicable Programs Sorted by Days until Window Closes

,name,university,availability,application_fee,window_start,window_end,specializations
28,Neural and Behavioural Sciences,University of Tuebingen,not-closed,None,NaN,14,"[Brain Imaging and Recording, Cognitive Neuros..."
15,Applied Computer Science,University of Goettingen,opened,0,-2.0,29,"[Applied System Engineering, Bioinformatics, B..."
14,Computer and Information Science,University of Konstanz,not-opened,None,1.0,29,"[Algorithmics, Data science, Interactive syste..."
2,Computer Science,University of Siegen,opened,0,-75.0,44,"[Complex and Intelligent Software Systems, Emb..."
23,Cognitive Science,Rhineland-Palatinate Technical University of K...,opened,60,-22.0,44,"[Cognition and Knowledge, Cognitive Neuroscien..."
29,Neuroscience,University of Oldenburg,opened,75/30,-2.0,44,"[Behavioural Neuroscience, Computational Neuro..."
30,Neuroscience,University of Bremen,opened,None,-16.0,44,"[Computational Neuroscience, Experimental Neur..."
3,Computer Science,University of Bonn,not-opened,0,29.0,45,"[Algorithmics, Graphics/Vision/Audio, Informat..."
26,Cognitive Systems,University of Ulm,not-opened,75/30,15.0,59,"[Interaction, Learning and Memory, Methods, Ge..."
13,Computer Science,Saarland University,not-closed,None,NaN,59,"[Cryptography, Distributed Information and Com..."
10,Computer Science,University of Freiburg,not-opened,0,29.0,75,"[Artificial Intelligence, Cyber-Physical Systems]"
11,Computer Science International,University of Rostock,not-opened,75/30,15.0,75,"[Complex Systems, Information Systems]"
4,Computer Science,University of Hannover,not-opened,75/30,29.0,75,"[Data Science, Human Centered Computing, Syste..."
8,Computer Science,Paderborn University,not-closed,75/30,NaN,75,"[Classical and Quantum Algorithm Design, Compu..."
12,Computer Science,University of Potsdam,not-opened,0,15.0,76,"[Algorithms and Foundations, Data and AI, Digi..."
24,Cognitive Science,University of Potsdam,not-opened,0,15.0,76,"[Advanced Natural Language Processing, Cogniti..."
6,Computer Science,University of Regensburg,not-opened,75/30,29.0,76,"[Bioinformatics, Core Computer Science, Human-..."
27,"Mind, Brain and Behavior",University of Giessen,opened,75/30,-106.0,90,"[Current Topics in Cognition and Development, ..."
22,Cognitive Science,University of Osnabrueck,not-opened,75/30,51.0,90,"[Cognition: (Computational) Neuroscience, Cogn..."
16,Web and Data Science,University of Koblenz,not-closed,75/30,NaN,90,"[Data Science, Engineering Web and Data-intens..."
5,Computer Science,Karlsruhe Institute of Technology,not-closed,None,NaN,90,"[Algorithm Engineering, Computer Graphics and ..."
19,Software Engineering,University of Hildesheim,not-opened,75/30,29.0,105,"[Advanced Web Development, Model-Based Softwar..."
9,Computer Science,University of Marburg,not-opened,75/30,45.0,105,"[Artificial Intelligence, Cloud Computing, Dat..."
18,International Software Systems Science,Bamberg University,not-opened,0,59.0,120,"[Communication Systems and Protocols, Distribu..."
1,Computer Science,Technical University of Hamburg,not-opened,0,76.0,120,"[Computer and Software Engineering, Intelligen..."
20,Web Engineering,Chemnitz University of Technology,not-opened,75/30,15.0,120,"[Databases, Information Systems, Internet and ..."
21,Cognitive Science,Ruhr University Bochum,not-opened,None,76.0,120,"[Brain and Behavior, Computation and Artificia..."

In [6]:
with pd.option_context("display.max_colwidth", None):
    display(Markdown("## Applicable Programs' Specialiaztions"))
    display(
        programs[programs["window_end"] >= 0].assign(
            specializations=lambda d: d["specializations"].map(
                lambda x: ", ".join(x) if isinstance(x, (list, tuple, set)) else x
            )
        )[["name", "university", "specializations"]]
    )

## Applicable Programs' Specialiaztions

,name,university,specializations
1,Computer Science,Technical University of Hamburg,"Computer and Software Engineering, Intelligence Engineering, Mathematics"
2,Computer Science,University of Siegen,"Complex and Intelligent Software Systems, Embedded Systems, Visual Computing"
3,Computer Science,University of Bonn,"Algorithmics, Graphics/Vision/Audio, Information and Communication Management, Intelligent Systems"
4,Computer Science,University of Hannover,"Data Science, Human Centered Computing, Systems-oriented Computer Science"
5,Computer Science,Karlsruhe Institute of Technology,"Algorithm Engineering, Computer Graphics and Geometry Processing, Data Science, Design of Embedded Systems and Computer Architectures, Human-centred Machine Intelligence, Parallel Computing, Robotics and Automation, Software Engineering and Compiler Construction, Telematics, Theoretical Foundations"
6,Computer Science,University of Regensburg,"Bioinformatics, Core Computer Science, Human-Centred Computing, Information Systems"
8,Computer Science,Paderborn University,"Classical and Quantum Algorithm Design, Computer and Communication Systems, Data Science and Intelligent Systems, Security, Software Engineering"
9,Computer Science,University of Marburg,"Artificial Intelligence, Cloud Computing, Databases, Distributed Systems, Graphics Programming, IT Security, Model Checking, Software Design"
10,Computer Science,University of Freiburg,"Artificial Intelligence, Cyber-Physical Systems"
11,Computer Science International,University of Rostock,"Complex Systems, Information Systems"
12,Computer Science,University of Potsdam,"Algorithms and Foundations, Data and AI, Digital Health, Security Engineering, Systems"
13,Computer Science,Saarland University,"Cryptography, Distributed Information and Communications Systems, Image Processing, Language Processing, Multimedia Applications, Program Analysis and Formal Methods"
14,Computer and Information Science,University of Konstanz,"Algorithmics, Data science, Interactive systems, Software and systems, Visual computing"
15,Applied Computer Science,University of Goettingen,"Applied System Engineering, Bioinformatics, Business Information Systems, Computational Neuroscience, Data Science, Digital Humanities, Ecological Informatics, Geoinformatics, Law and Computer Science, Medical Informatics, Scientific Computing"
16,Web and Data Science,University of Koblenz,"Data Science, Engineering Web and Data-intensive Systems, Machine Learning and Data Mining, Network Theory and Dynamic Systems, Web Science"
18,International Software Systems Science,Bamberg University,"Communication Systems and Protocols, Distributed and Mobile Systems, Service-oriented Architectures, Software Analysis and Verification"
19,Software Engineering,University of Hildesheim,"Advanced Web Development, Model-Based Software Engineering, Requirements Engineering for Quality, Software Architectures, Software Engineering, Software Product Line Engineering"
20,Web Engineering,Chemnitz University of Technology,"Databases, Information Systems, Internet and Web Technologies, Software Engineering"
21,Cognitive Science,Ruhr University Bochum,"Brain and Behavior, Computation and Artificial Intelligence, Mind and Language"
22,Cognitive Science,University of Osnabrueck,"Cognition: (Computational) Neuroscience, Cognition: Artificial Intelligence and Machine Learning, Cognition: Mind, Ethics, and Society, Cognition: Psychology, Language, and Communication"
23,Cognitive Science,Rhineland-Palatinate Technical University of Kaiserslautern-Landau,"Cognition and Knowledge, Cognitive Neuroscience, Computation, Language and Linguistics, Perception"
24,Cognitive Science,University of Potsdam,"Advanced Natural Language Processing, Cognition, Cognitive Development, Cognitive Modeling, Cognitive Neuroscience, Evidence Bases for Language Disorders, First Language Acquisition, Language Processing"
26,Cognitive Systems,University of Ulm,"Interaction, Learning and Memory, Methods, General Concepts and Tools, Perception, Planning and Reasoning"
27,"Mind, Brain and Behavior",University of Giessen,"Current Topics in Cognition and Development, Perception and Action, Visual Cognition and Object Perception, Visual Perception of Color and Materials"
28,Neural and Behavioural Sciences,University of Tuebingen,"Brain Imaging and Recording, Cognitive Neuroscience and Psychophysics, Computational Neuroscience, Functional Neuroanatomy, Learning and Memory, Motor and Sensory Systems Neuroscience, Neurophysiology and Neuropsychology"
29,Neuroscience,University of Oldenburg,"Behavioural Neuroscience, Computational Neuroscience, Sensory Neuroscience"
30,Neuroscience,University of Bremen,"Computational Neuroscience, Experimental Neuroscience"