In [1]:
from datetime import date

import pandas as pd
from IPython.display import Markdown

from data import PROGRAMS
from models import AVAILABILITY_TYPES, Semester

In [2]:
display(Markdown(f"## This notebook is run on {date.today()}"))

## This notebook is run on 2026-04-17

In [3]:
TARGET_SEMESTER = Semester(starting_year="2026", season="winter")

In [4]:
programs = pd.DataFrame(
    [
        {
            "name": p.name,
            "university": p.university_name,
            "availability": p.get_availability(TARGET_SEMESTER),
            "application_fee": p.application_fee,
            "window_start": p.get_days_until_window_starts(TARGET_SEMESTER),
            "window_end": p.get_days_until_window_ends(TARGET_SEMESTER),
            "specializations": p.specializations,
        }
        for p in PROGRAMS
    ]
)

In [5]:
for a in AVAILABILITY_TYPES:
    display(Markdown(f"## {a.upper()}"))
    display(programs[programs["availability"] == a])

## CLOSED

,name,university,availability,application_fee,window_start,window_end,specializations
0,Computer Science,University of Stuttgart,closed,0.0,-153.0,-92,"[Autonomous Systems in Computer Science, Servi..."
7,Computer Science,Ruhr University Bochum,closed,NaN,-167.0,-123,"[Artificial Intelligence, Cybersecurity, Quant..."
14,Computer and Information Science,University of Konstanz,closed,NaN,-30.0,-2,"[Algorithmics, Data science, Interactive syste..."
15,Applied Computer Science,University of Goettingen,closed,0.0,-33.0,-2,"[Applied System Engineering, Bioinformatics, B..."
17,Software Systems Engineering,RWTH Aachen University,closed,0.0,-137.0,-47,"[Applied Computer Science, Communication, Data..."
25,Cognitive Science,Technical University of Darmstadt,closed,NaN,-137.0,-47,"[Applied Cognitive Science, Artificial Intelli..."
28,Neural and Behavioural Sciences,University of Tuebingen,closed,NaN,NaN,-17,"[Brain Imaging and Recording, Cognitive Neuros..."
32,Computer Science,University of Bari Aldo Moro,closed,NaN,NaN,-48,"[Artificial Intelligence, Security Engineering]"
33,Computer Science,University of Camerino,closed,20.0,NaN,-17,"[Artificial Intelligence, Business Information..."
34,Computer Science,University of Genoa,closed,30.0,-142.0,-28,"[Data Science & Engineering, Software Security..."
35,Computer Science and Engineering,Politecnico di Milano,closed,NaN,-94.0,-50,"[Ambient and data intelligence, Artificial int..."
38,Computer Science,University of Pisa,closed,30.0,-137.0,-71,"[Artificial Intelligence, Big Data Technologie..."
40,Computer Science,University of Trento,closed,30.0,NaN,-44,"[Computer Science and Technologies, ICT Innova..."

## NOT-OPENED

,name,university,availability,application_fee,window_start,window_end,specializations
1,Computer Science,Technical University of Hamburg,not-opened,0.0,45.0,89,"[Computer and Software Engineering, Intelligen..."
9,Computer Science,University of Marburg,not-opened,30.0,14.0,74,"[Artificial Intelligence, Cloud Computing, Dat..."
18,International Software Systems Science,Bamberg University,not-opened,0.0,28.0,89,"[Communication Systems and Protocols, Distribu..."
21,Cognitive Science,Ruhr University Bochum,not-opened,NaN,45.0,89,"[Brain and Behavior, Computation and Artificia..."
22,Cognitive Science,University of Osnabrueck,not-opened,30.0,20.0,59,"[Cognition: (Computational) Neuroscience, Cogn..."

## OPENED

,name,university,availability,application_fee,window_start,window_end,specializations
2,Computer Science,University of Siegen,opened,0.0,-106.0,13,"[Complex and Intelligent Software Systems, Emb..."
3,Computer Science,University of Bonn,opened,0.0,-2.0,14,"[Algorithmics, Graphics/Vision/Audio, Informat..."
4,Computer Science,University of Hannover,opened,30.0,-2.0,44,"[Data Science, Human Centered Computing, Syste..."
6,Computer Science,University of Regensburg,opened,30.0,-2.0,45,"[Bioinformatics, Core Computer Science, Human-..."
10,Computer Science,University of Freiburg,opened,0.0,-2.0,44,"[Artificial Intelligence, Cyber-Physical Systems]"
11,Computer Science International,University of Rostock,opened,30.0,-16.0,44,"[Complex Systems, Information Systems]"
12,Computer Science,University of Potsdam,opened,0.0,-16.0,45,"[Algorithms and Foundations, Data and AI, Digi..."
19,Software Engineering,University of Hildesheim,opened,30.0,-2.0,74,"[Advanced Web Development, Model-Based Softwar..."
20,Web Engineering,Chemnitz University of Technology,opened,30.0,-16.0,89,"[Databases, Information Systems, Internet and ..."
23,Cognitive Science,Rhineland-Palatinate Technical University of K...,opened,60.0,-53.0,13,"[Cognition and Knowledge, Cognitive Neuroscien..."
24,Cognitive Science,University of Potsdam,opened,0.0,-16.0,45,"[Advanced Natural Language Processing, Cogniti..."
26,Cognitive Systems,University of Ulm,opened,30.0,-16.0,28,"[Interaction, Learning and Memory, Methods, Ge..."
27,"Mind, Brain and Behavior",University of Giessen,opened,30.0,-137.0,59,"[Current Topics in Cognition and Development, ..."
29,Neuroscience,University of Oldenburg,opened,30.0,-33.0,13,"[Behavioural Neuroscience, Computational Neuro..."
30,Neuroscience,University of Bremen,opened,NaN,-47.0,13,"[Computational Neuroscience, Experimental Neur..."
31,Cognitive Science,University of Trento,opened,30.0,-67.0,42,"[Cognitive Neuroscience, Computational and The..."
36,Engineering in Computer Science,University of Messina,opened,30.0,-4.0,23,None
37,Computer Science,University of Padua,opened,60.0,-46.0,15,None
39,Computer Science,Sapienza University of Rome,opened,30.0,-116.0,28,None
41,Software Engineering,Free University of Bozen-Bolzano,opened,50.0,-46.0,11,None

## NOT-CLOSED

,name,university,availability,application_fee,window_start,window_end,specializations
5,Computer Science,Karlsruhe Institute of Technology,not-closed,NaN,NaN,59,"[Algorithm Engineering, Computer Graphics and ..."
8,Computer Science,Paderborn University,not-closed,30.0,NaN,44,"[Classical and Quantum Algorithm Design, Compu..."
13,Computer Science,Saarland University,not-closed,NaN,NaN,28,"[Cryptography, Distributed Information and Com..."
16,Web and Data Science,University of Koblenz,not-closed,30.0,NaN,59,"[Data Science, Engineering Web and Data-intens..."

In [6]:
display(Markdown("## Applicable Programs Sorted by Days until Window Closes"))
with pd.option_context("display.max_colwidth", None):
    display(
        programs[programs["window_end"] >= 0]
        .assign(
            specializations=lambda d: d["specializations"].map(
                lambda x: ", ".join(x) if isinstance(x, (list, tuple, set)) else x
            )
        )
        .sort_values(by=["window_end", "application_fee", "window_start"])
    )

# with pd.option_context("display.max_colwidth", None):
#     display(Markdown("## Applicable Programs' Specialiaztions"))
#     display(
#         programs[programs["window_end"] >= 0].assign(
#             specializations=lambda d: d["specializations"].map(
#                 lambda x: ", ".join(x) if isinstance(x, (list, tuple, set)) else x
#             )
#         )[["name", "university", "specializations"]]
#     )

## Applicable Programs Sorted by Days until Window Closes

,name,university,availability,application_fee,window_start,window_end,specializations
41,Software Engineering,Free University of Bozen-Bolzano,opened,50.0,-46.0,11,NaN
2,Computer Science,University of Siegen,opened,0.0,-106.0,13,"Complex and Intelligent Software Systems, Embedded Systems, Visual Computing"
29,Neuroscience,University of Oldenburg,opened,30.0,-33.0,13,"Behavioural Neuroscience, Computational Neuroscience, Sensory Neuroscience"
23,Cognitive Science,Rhineland-Palatinate Technical University of Kaiserslautern-Landau,opened,60.0,-53.0,13,"Cognition and Knowledge, Cognitive Neuroscience, Computation, Language and Linguistics, Perception"
30,Neuroscience,University of Bremen,opened,NaN,-47.0,13,"Computational Neuroscience, Experimental Neuroscience"
3,Computer Science,University of Bonn,opened,0.0,-2.0,14,"Algorithmics, Graphics/Vision/Audio, Information and Communication Management, Intelligent Systems"
37,Computer Science,University of Padua,opened,60.0,-46.0,15,NaN
36,Engineering in Computer Science,University of Messina,opened,30.0,-4.0,23,NaN
39,Computer Science,Sapienza University of Rome,opened,30.0,-116.0,28,NaN
26,Cognitive Systems,University of Ulm,opened,30.0,-16.0,28,"Interaction, Learning and Memory, Methods, General Concepts and Tools, Perception, Planning and Reasoning"
13,Computer Science,Saarland University,not-closed,NaN,NaN,28,"Cryptography, Distributed Information and Communications Systems, Image Processing, Language Processing, Multimedia Applications, Program Analysis and Formal Methods"
31,Cognitive Science,University of Trento,opened,30.0,-67.0,42,"Cognitive Neuroscience, Computational and Theoretical Modelling of Language and Cognition, fundamental Behavioural Neuroscience"
10,Computer Science,University of Freiburg,opened,0.0,-2.0,44,"Artificial Intelligence, Cyber-Physical Systems"
11,Computer Science International,University of Rostock,opened,30.0,-16.0,44,"Complex Systems, Information Systems"
4,Computer Science,University of Hannover,opened,30.0,-2.0,44,"Data Science, Human Centered Computing, Systems-oriented Computer Science"
8,Computer Science,Paderborn University,not-closed,30.0,NaN,44,"Classical and Quantum Algorithm Design, Computer and Communication Systems, Data Science and Intelligent Systems, Security, Software Engineering"
12,Computer Science,University of Potsdam,opened,0.0,-16.0,45,"Algorithms and Foundations, Data and AI, Digital Health, Security Engineering, Systems"
24,Cognitive Science,University of Potsdam,opened,0.0,-16.0,45,"Advanced Natural Language Processing, Cognition, Cognitive Development, Cognitive Modeling, Cognitive Neuroscience, Evidence Bases for Language Disorders, First Language Acquisition, Language Processing"
6,Computer Science,University of Regensburg,opened,30.0,-2.0,45,"Bioinformatics, Core Computer Science, Human-Centred Computing, Information Systems"
27,"Mind, Brain and Behavior",University of Giessen,opened,30.0,-137.0,59,"Current Topics in Cognition and Development, Perception and Action, Visual Cognition and Object Perception, Visual Perception of Color and Materials"
22,Cognitive Science,University of Osnabrueck,not-opened,30.0,20.0,59,"Cognition: (Computational) Neuroscience, Cognition: Artificial Intelligence and Machine Learning, Cognition: Mind, Ethics, and Society, Cognition: Psychology, Language, and Communication"
16,Web and Data Science,University of Koblenz,not-closed,30.0,NaN,59,"Data Science, Engineering Web and Data-intensive Systems, Machine Learning and Data Mining, Network Theory and Dynamic Systems, Web Science"
5,Computer Science,Karlsruhe Institute of Technology,not-closed,NaN,NaN,59,"Algorithm Engineering, Computer Graphics and Geometry Processing, Data Science, Design of Embedded Systems and Computer Architectures, Human-centred Machine Intelligence, Parallel Computing, Robotics and Automation, Software Engineering and Compiler Construction, Telematics, Theoretical Foundations"
19,Software Engineering,University of Hildesheim,opened,30.0,-2.0,74,"Advanced Web Development, Model-Based Software Engineering, Requirements Engineering for Quality, Software Architectures, Software Engineering, Software Product Line Engineering"
9,Computer Science,University of Marburg,not-opened,30.0,14.0,74,"Artificial Intelligence, Cloud Computing, Databases, Distributed Systems, Graphics Programming, IT Security, Model Checking, Software Design"
18,International Software Systems Science,Bamberg University,not-opened,0.0,28.0,89,"Communication Systems and Protocols, Distributed and Mobile Systems, Service-oriented Architectures, Software Analysis and Verification"
1,Computer Science,Technical University of Hamburg,not-opened,0.0,45.0,89,"Computer and Software Engineering, Intelligence Engineering, Mathematics"
20,Web Engineering,Chemnitz University of Technology,opened,30.0,-16.0,89,"Databases, Information Systems, Internet and Web Technologies, Software Engineering"
21,Cognitive Science,Ruhr University Bochum,not-opened,NaN,45.0,89,"Brain and Behavior, Computation and Artificial Intelligence, Mind and Language"